DR_EXPLAIN = DR_EXPLAIN || {};
DR_EXPLAIN.searchIndex = DR_EXPLAIN.searchIndex || {};
DR_EXPLAIN.searchIndex.prefixes = [
	{ "fileName": "0xu0030.js", "first": "001", "last": "01-1-ЛУ" },
	{ "fileName": "0xu0031.js", "first": "1", "last": "19" },
	{ "fileName": "0xu0032.js", "first": "2", "last": "21" },
	{ "fileName": "0xu0033.js", "first": "3", "last": "34" },
	{ "fileName": "0xu0034.js", "first": "4", "last": "4.4" },
	{ "fileName": "0xu0035.js", "first": "5", "last": "50-34.698-90" },
	{ "fileName": "0xu0036.js", "first": "698", "last": "698" },
	{ "fileName": "0xu0039.js", "first": "90", "last": "90" },
	{ "fileName": "0xu0041.js", "first": "ANASTASIAZEL", "last": "ANASTASIAZEL" },
	{ "fileName": "0xu0043.js", "first": "COM", "last": "CREATE" },
	{ "fileName": "0xu0044.js", "first": "DELETE", "last": "DELETE" },
	{ "fileName": "0xu0047.js", "first": "GOOGLE", "last": "GOOGLE-ФОРМОЙ" },
	{ "fileName": "0xu0048.js", "first": "HSE", "last": "HTTP://ANASTASIAZEL-001-SITE1.KTEMPURL.COM" },
	{ "fileName": "0xu004b.js", "first": "KTEMPURL", "last": "KTEMPURL" },
	{ "fileName": "0xu0052.js", "first": "RU", "last": "RU.17701729.12.17" },
	{ "fileName": "0xu0053.js", "first": "SITE1", "last": "SPORT" },
	{ "fileName": "0xu0410.js", "first": "А", "last": "АПРЕЛЯ" },
	{ "fileName": "0xu0411.js", "first": "БОЛЕЕ", "last": "БЫТЬ" },
	{ "fileName": "0xu0412.js", "first": "В", "last": "ВЫСШАЯ" },
	{ "fileName": "0xu0413.js", "first": "Г", "last": "ГОСТ" },
	{ "fileName": "0xu0414.js", "first": "Д", "last": "ДРУГОЙ" },
	{ "fileName": "0xu0415.js", "first": "ЕГО", "last": "ЕЩЕ" },
	{ "fileName": "0xu0417.js", "first": "ЗА", "last": "ЗНАЧЕНИЯ" },
	{ "fileName": "0xu0418.js", "first": "И", "last": "ИХ" },
	{ "fileName": "0xu041a.js", "first": "К", "last": "КУШЕВ" },
	{ "fileName": "0xu041b.js", "first": "ЛАНИН", "last": "ЛУ" },
	{ "fileName": "0xu041c.js", "first": "МЕНЕЕ", "last": "МОЖНО" },
	{ "fileName": "0xu041d.js", "first": "Н", "last": "НЫХ" },
	{ "fileName": "0xu041e.js", "first": "О", "last": "ОШИБОК" },
	{ "fileName": "0xu041f.js", "first": "П", "last": "ПРОСМОТРЕТЬ" },
	{ "fileName": "0xu0420.js", "first": "РАБОТЕ", "last": "РЯДОМ" },
	{ "fileName": "0xu0421.js", "first": "С", "last": "СТУДЕНТУ" },
	{ "fileName": "0xu0422.js", "first": "Т", "last": "ТРЕБУЕТСЯ" },
	{ "fileName": "0xu0423.js", "first": "У", "last": "УЧЕТНЫЕ" },
	{ "fileName": "0xu0424.js", "first": "ФАКТОРОМ", "last": "ФУНКЦИЯМ" },
	{ "fileName": "0xu0425.js", "first": "ХОТИТЕ", "last": "ХРАНИТЬ" },
	{ "fileName": "0xu0427.js", "first": "ЧАСТИ", "last": "ЧЬИ" },
	{ "fileName": "0xu0428.js", "first": "ШКОЛА", "last": "ШКОЛА" },
	{ "fileName": "0xu042d.js", "first": "ЭКОНОМИКИ", "last": "ЭТОГО" },
	{ "fileName": "0xu042f.js", "first": "ЯВЛЯЕТСЯ", "last": "ЯВЛЯЕТСЯ" }
];